name: Build (Java 8 / Spigot 1.16.5)
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: maven
      - run: mvn -B -q -DskipTests clean package
      - run: ls -al target || true
